name: Build and Deploy to TCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Replace database credentials in database.js
        run: |
          sed -i 's/hiolabsDB/${{ secrets.DB_NAME }}/g' ./src/common/config/database.js
          sed -i 's/127.0.0.1/${{ secrets.DB_HOST }}/g' ./src/common/config/database.js
          sed -i 's/3306/${{ secrets.DB_PORT }}/g' ./src/common/config/database.js
          sed -i 's/root/${{ secrets.DB_USER }}/g' ./src/common/config/database.js
          sed -i 's/123123123/${{ secrets.DB_PASSWORD }}/g' ./src/common/config/database.js

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.TCR_IMAGE_NAME }} .

      - name: Log in to Tencent Cloud Registry (TCR)
        run: |
          echo ${{ secrets.TCR_PASSWORD }} | docker login ccr.ccs.tencentyun.com --username=${{ secrets.TCR_USERNAME }} --password-stdin

      - name: Tag Docker image for TCR
        run: |
          docker tag ${{ secrets.TCR_IMAGE_NAME }}:latest ccr.ccs.tencentyun.com/${{ secrets.TCR_REPOSITORY }}:${{ secrets.TCR_TAG }}

      - name: Push Docker image to TCR
        run: |
          docker push ccr.ccs.tencentyun.com/${{ secrets.TCR_REPOSITORY }}:${{ secrets.TCR_TAG }}
