name: Install and Run Speedtest-cli

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update and Upgrade System
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Install speedtest-cli
      run: |
        sudo apt install -y speedtest-cli

    - name: Run speedtest-cli
      run: |
        speedtest-cli
